//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Main {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Main {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Main() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Main.Main", typeof(Main).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شركة تك تاتش قام بإنشاء الشركة مجموعة متميزة من مهندسى الكمبيوتر ونظم المعلومات ذوى خبرة عريضة فى مجالي البرمجة و الإدارة المالية, تهدف شركة تك تاتش تقديم برمجيات عالية الجودة بالمقاييس العالمية للقطاعات المالية والتجارية في الوطن العربي و نظرا لخبراتنا الواسعة في مجال البرمجيات فقد وضعت الشركة في اعتبارها منذ بدء التخطيط لبرامجها ان تكون كافة برامج الشركة سهلة الإستخدام وتسمح بالتوسع والإمتداد مع زيادة وتوسع إحتياجات العملاء, تقدم الشركة كذلك خدمات الدعم الفني لعملائها . شركة تك تاتش دائما في خدمة عملائها  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string About_Company {
            get {
                return ResourceManager.GetString("About_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ماذا عنا.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وصول.
        /// </summary>
        public static string Access {
            get {
                return ResourceManager.GetString("Access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصول من اي مكان.
        /// </summary>
        public static string Access_from_anywhere {
            get {
                return ResourceManager.GetString("Access_from_anywhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هو برنامج محاسبي متكامل يساعدك هذا البرنامج علي اداره كافه المعاملات الماليه والمحاسبيه ومتابعتها من اي مكان في العالم بدون مشاكل.
        /// </summary>
        public static string Accounting_Software {
            get {
                return ResourceManager.GetString("Accounting_Software", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التحصيل وتحليل الكفاءة الأساسي.
        /// </summary>
        public static string Achievement {
            get {
                return ResourceManager.GetString("Achievement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاكشن.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الإضافة بنجاح..
        /// </summary>
        public static string AddedSuccessfully {
            get {
                return ResourceManager.GetString("AddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ فى عملية الإضافة .
        /// </summary>
        public static string AddFailure {
            get {
                return ResourceManager.GetString("AddFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدير المسئول في .
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صباحا.
        /// </summary>
        public static string am {
            get {
                return ResourceManager.GetString("am", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إعلان للمجموعة.
        /// </summary>
        public static string Announcement_to_group {
            get {
                return ResourceManager.GetString("Announcement_to_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قد سجل مستخدم اخر قبلك بلحظات شركة تحمل نفس الاسم العربي.
        /// </summary>
        public static string Another_user_registered_with_arabic_name {
            get {
                return ResourceManager.GetString("Another_user_registered_with_arabic_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قد سجل مستخدم اخر قبلك بلحظات شركة تحمل نفس الاسم الانجليزي.
        /// </summary>
        public static string Another_user_registered_with_english_name {
            get {
                return ResourceManager.GetString("Another_user_registered_with_english_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قد سجل مستخدم اخر قبلك بلحظات شركة تحمل نفس التليفون.
        /// </summary>
        public static string Another_user_registered_with_phone {
            get {
                return ResourceManager.GetString("Another_user_registered_with_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اي استفسارات ؟.
        /// </summary>
        public static string Any_Questions {
            get {
                return ResourceManager.GetString("Any_Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحة وصف التطبيق..
        /// </summary>
        public static string App_Description {
            get {
                return ResourceManager.GetString("App_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مميزات التطبيق.
        /// </summary>
        public static string App_Features {
            get {
                return ResourceManager.GetString("App_Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عربي.
        /// </summary>
        public static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مكان.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يقوم هذا البرنامج باداره اصولك باستخدام عمليه اداره الاصول من البدايه اللي النهايه منذ الوقت الذي يتم فيه الشراء لاول مره الي فتره التهايه وهذا البرنامج يساعدك علي تتبع اصولك بشكل مستمر.
        /// </summary>
        public static string Assets_Management {
            get {
                return ResourceManager.GetString("Assets_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المرفقات.
        /// </summary>
        public static string Attachements {
            get {
                return ResourceManager.GetString("Attachements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجوع الي المجموعة.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحليل الكفاءة الأساسي.
        /// </summary>
        public static string Basic_competence_analysis {
            get {
                return ResourceManager.GetString("Basic_competence_analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المواد الاساسية للتعليم /الدروس.
        /// </summary>
        public static string Basic_learning {
            get {
                return ResourceManager.GetString("Basic_learning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القائمة الاساسية.
        /// </summary>
        public static string Basic_Menu {
            get {
                return ResourceManager.GetString("Basic_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المهمة الأساسية / الاختبار / النص.
        /// </summary>
        public static string Basic_task {
            get {
                return ResourceManager.GetString("Basic_task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نموزج اساسي.
        /// </summary>
        public static string Basic_Template {
            get {
                return ResourceManager.GetString("Basic_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اصعد بعملك إلى آفاق جديدة باستخدام أدوات قوية وفعالة تعزز وتقوي عمليات عملك..
        /// </summary>
        public static string business {
            get {
                return ResourceManager.GetString("business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اشترك الآن.
        /// </summary>
        public static string BuyNow {
            get {
                return ResourceManager.GetString("BuyNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تواصل معنا الان.
        /// </summary>
        public static string Call_Us_Now {
            get {
                return ResourceManager.GetString("Call_Us_Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نحن نهتم بعملائنا.
        /// </summary>
        public static string Care_Customer {
            get {
                return ResourceManager.GetString("Care_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإدارة العليا.
        /// </summary>
        public static string Class_management {
            get {
                return ResourceManager.GetString("Class_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعليق / مناقشة الإدارة.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البحث عن شركة.
        /// </summary>
        public static string Company_Search {
            get {
                return ResourceManager.GetString("Company_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم انشاء شركة.
        /// </summary>
        public static string Company_was_created {
            get {
                return ResourceManager.GetString("Company_was_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الشركات.
        /// </summary>
        public static string CompanyCount {
            get {
                return ResourceManager.GetString("CompanyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لينك الشركة.
        /// </summary>
        public static string CompanyLink {
            get {
                return ResourceManager.GetString("CompanyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أوراق عمل كاملة.
        /// </summary>
        public static string Complete_Worksheets {
            get {
                return ResourceManager.GetString("Complete_Worksheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إتصل بنا.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات الاتصال.
        /// </summary>
        public static string ContactInfo {
            get {
                return ResourceManager.GetString("ContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكنترولر.
        /// </summary>
        public static string Controller {
            get {
                return ResourceManager.GetString("Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جميع الحقوق محفوظة.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدول.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يمنحك المساند حريه الوصول اللي التطبيق من اي مكان وفي اي وقت ومن اي جهاز الان المساند يعتمد علي السحابه..
        /// </summary>
        public static string cushions {
            get {
                return ResourceManager.GetString("cushions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقرير العميل .
        /// </summary>
        public static string Custmer_Report {
            get {
                return ResourceManager.GetString("Custmer_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجال مخصص.
        /// </summary>
        public static string Custom_Domain {
            get {
                return ResourceManager.GetString("Custom_Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقارير العميل.
        /// </summary>
        public static string Customer_Report {
            get {
                return ResourceManager.GetString("Customer_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدعم الفني المباشر.
        /// </summary>
        public static string Customer_Support {
            get {
                return ResourceManager.GetString("Customer_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كود العميل.
        /// </summary>
        public static string CustomerCode {
            get {
                return ResourceManager.GetString("CustomerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العملاء.
        /// </summary>
        public static string CustomerList {
            get {
                return ResourceManager.GetString("CustomerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كل ماهو متعلق بالعملاء.
        /// </summary>
        public static string CustomerService {
            get {
                return ResourceManager.GetString("CustomerService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شراء العملاء.
        /// </summary>
        public static string CustomersPurchase {
            get {
                return ResourceManager.GetString("CustomersPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مهمة قابلة للتخصيص.
        /// </summary>
        public static string Customizable {
            get {
                return ResourceManager.GetString("Customizable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تؤمن المساند المعلومات الهامه او الخاصه بك مع افضل خوارزميات التشفير للحفاظ علي حسابك وبياناتك ومعلوماتك الشخصيه امنه..
        /// </summary>
        public static string Datasets_secure {
            get {
                return ResourceManager.GetString("Datasets_secure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd.
        /// </summary>
        public static string dd {
            get {
                return ResourceManager.GetString("dd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف البيانات.
        /// </summary>
        public static string Delete_data {
            get {
                return ResourceManager.GetString("Delete_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم العثور علي الملف.
        /// </summary>
        public static string DeletedNotFound {
            get {
                return ResourceManager.GetString("DeletedNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الحذف بنجاح..
        /// </summary>
        public static string DeletedSuccessfully {
            get {
                return ResourceManager.GetString("DeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ عند الحذف.
        /// </summary>
        public static string DeleteFailure {
            get {
                return ResourceManager.GetString("DeleteFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم الحذف لوجود ملفات مرتبطة بهذا الملف.
        /// </summary>
        public static string DeleteFoundRelated {
            get {
                return ResourceManager.GetString("DeleteFoundRelated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التسويق الالكتروني.
        /// </summary>
        public static string digital_marketing {
            get {
                return ResourceManager.GetString("digital_marketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم التعديل بنجاح..
        /// </summary>
        public static string EditedSuccessfully {
            get {
                return ResourceManager.GetString("EditedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ فى عملية التعديل ...
        /// </summary>
        public static string EditFailure {
            get {
                return ResourceManager.GetString("EditFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نموزج للبريد الالكتروني.
        /// </summary>
        public static string Email_template {
            get {
                return ResourceManager.GetString("Email_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المسوقين الاكترونين.
        /// </summary>
        public static string EMarketer_Users {
            get {
                return ResourceManager.GetString("EMarketer_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المسوقين.
        /// </summary>
        public static string EMarketers {
            get {
                return ResourceManager.GetString("EMarketers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انجليزي.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERP صفحات الـ.
        /// </summary>
        public static string ErpPages {
            get {
                return ResourceManager.GetString("ErpPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ أثناء معالجة طلبك..
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ.
        /// </summary>
        public static string ErrorLabel {
            get {
                return ResourceManager.GetString("ErrorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إستثناء.
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمييز الوجوه.
        /// </summary>
        public static string Face_Recognition {
            get {
                return ResourceManager.GetString("Face_Recognition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأسئلة الشائعة.
        /// </summary>
        public static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الميزات.
        /// </summary>
        public static string Features {
            get {
                return ResourceManager.GetString("Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لاستخدامها ، تخدم القطاع المالي والتجاري.
        /// </summary>
        public static string Financial {
            get {
                return ResourceManager.GetString("Financial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المحاسبة المالية.
        /// </summary>
        public static string Financial_Accounting {
            get {
                return ResourceManager.GetString("Financial_Accounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ألاصول ثابتة.
        /// </summary>
        public static string Fixed_Assets {
            get {
                return ResourceManager.GetString("Fixed_Assets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برنامج الاصول الثابتة.
        /// </summary>
        public static string FixedAssetsProgram {
            get {
                return ResourceManager.GetString("FixedAssetsProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برنامج حسابات مرن.
        /// </summary>
        public static string Flexible_accounting_software {
            get {
                return ResourceManager.GetString("Flexible_accounting_software", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نحن جاهزون دائمًا لمساعدة العملاء و بناء علاقة قوية ولهذا السبب فريق الدعم لدينا موجود دائمًا لمساعدتهم.
        /// </summary>
        public static string FooterContent {
            get {
                return ResourceManager.GetString("FooterContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجانا.
        /// </summary>
        public static string Free {
            get {
                return ResourceManager.GetString("Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انشاء.
        /// </summary>
        public static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برنامج الحسابات العامة.
        /// </summary>
        public static string GlobalAccountProgram {
            get {
                return ResourceManager.GetString("GlobalAccountProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المجموعات.
        /// </summary>
        public static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرحبا.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نحن مستعدون دائمًا لمساعدة العملاء لبناء علاقة قوية ولهذا السبب فريق الدعم لدينا موجود دائمًا لمساعدتهم.
        /// </summary>
        public static string help_Customer {
            get {
                return ResourceManager.GetString("help_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرئيسية.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموارد البشرية.
        /// </summary>
        public static string HR {
            get {
                return ResourceManager.GetString("HR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يقدم لك البرنامج الداش بورد يحتوي علي مجموعات كبيره من المخططات البيانيه والذي صمم بطريقه انحرافيه تسمح للمدارء بمراقبه الاعمال ومعرفه النتائج واتخاذ القرارات بالوقت المناسب.
        /// </summary>
        public static string HR_Description {
            get {
                return ResourceManager.GetString("HR_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استيراد/ تصدير البيانات للطالب.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امن متكامل للبيانات.
        /// </summary>
        public static string Integrated_data_security {
            get {
                return ResourceManager.GetString("Integrated_data_security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يقدم لك هذا البرنامج نظام متجر التسويق الالكتروني مما يساعدك علي سهوله عرض مشروعك بكامل عبر التسويق الالكتروني.
        /// </summary>
        public static string interchangable {
            get {
                return ResourceManager.GetString("interchangable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المخزون.
        /// </summary>
        public static string inventory {
            get {
                return ResourceManager.GetString("inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برنامج اداره المخزون.
        /// </summary>
        public static string InventoryManagementProgram {
            get {
                return ResourceManager.GetString("InventoryManagementProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سهوله زياده الاصناف ويقوم بالترحيل اللي المخازن والحسابات العامه والارباح وحسابات العملاء
        ///والموردين وفتح اكثر من مخزن واكثر من فرع ولكل فرع له اسعار خاصه منصله عن باقي
        ///الفروع وعدد لا محدود من الاصناف بجميع اسعارها ومواصفاتها والتحكم الكامل في المخزون
        ///ومعرفه كل فرع بالاصناف اللازمه.
        /// </summary>
        public static string invoices {
            get {
                return ResourceManager.GetString("invoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان IP.
        /// </summary>
        public static string IPAdress {
            get {
                return ResourceManager.GetString("IPAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اللغة.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موقعنا.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم قفل هذا الحساب ، يرجى المحاولة مرة أخرى لاحقًا..
        /// </summary>
        public static string lockedAccount {
            get {
                return ResourceManager.GetString("lockedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الاغلاق.
        /// </summary>
        public static string Lockedout {
            get {
                return ResourceManager.GetString("Lockedout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدخول.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروج.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإدارة.
        /// </summary>
        public static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ التعديل.
        /// </summary>
        public static string ModificationDate {
            get {
                return ResourceManager.GetString("ModificationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النمازج.
        /// </summary>
        public static string Module {
            get {
                return ResourceManager.GetString("Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ربط الصفحات بالنمازج.
        /// </summary>
        public static string ModulePages {
            get {
                return ResourceManager.GetString("ModulePages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوحدات.
        /// </summary>
        public static string Modules {
            get {
                return ResourceManager.GetString("Modules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ما نقوم به هو توفير برامج عالية الجودة وهي سهلة.
        /// </summary>
        public static string More_than {
            get {
                return ResourceManager.GetString("More_than", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العملاء الغير مفعلين.
        /// </summary>
        public static string NotActivatedCustomer {
            get {
                return ResourceManager.GetString("NotActivatedCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لايوجد.
        /// </summary>
        public static string notfound {
            get {
                return ResourceManager.GetString("notfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إشعار بإنشاء شركة جديدة.
        /// </summary>
        public static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طريق ميكروسوفت الاول.
        /// </summary>
        public static string One_Microsoft_Way {
            get {
                return ResourceManager.GetString("One_Microsoft_Way", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تدريب أونلاين.
        /// </summary>
        public static string OnlineTraing {
            get {
                return ResourceManager.GetString("OnlineTraing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساعات العمل.
        /// </summary>
        public static string Opening_Hours {
            get {
                return ResourceManager.GetString("Opening_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عمليات.
        /// </summary>
        public static string Operations {
            get {
                return ResourceManager.GetString("Operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم السرى.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رسالة شخصية.
        /// </summary>
        public static string Personal_message {
            get {
                return ResourceManager.GetString("Personal_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظام اداره الشؤن الموظفين.
        /// </summary>
        public static string PersonnelManagementSystem {
            get {
                return ResourceManager.GetString("PersonnelManagementSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموقع.
        /// </summary>
        public static string Place {
            get {
                return ResourceManager.GetString("Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مساءا.
        /// </summary>
        public static string pm {
            get {
                return ResourceManager.GetString("pm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظام اداره نقاط البيع.
        /// </summary>
        public static string PointOfSaleManagementSystem {
            get {
                return ResourceManager.GetString("PointOfSaleManagementSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اداره نقاط البيع.
        /// </summary>
        public static string POS_Management {
            get {
                return ResourceManager.GetString("POS_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظام اداره نقاط البيع يعمل هذا البرنامج علي البيع التجزئه ويتميز هذا البرنامج المخصص لهذا البيع بانه سهل جدا ويمكن استخدامه بحسب نشاط ونوع اي منشاه ويتعامل مع اجهزه المسح الضوئي لقراءه الباركود الخاص ويتوافق مع جميع انظمه البيع والكاشير.
        /// </summary>
        public static string POS_Management_Software {
            get {
                return ResourceManager.GetString("POS_Management_Software", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نموزج مميز.
        /// </summary>
        public static string Premium_Template {
            get {
                return ResourceManager.GetString("Premium_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * سعر المستخدم / الشهر.
        /// </summary>
        public static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأسعار.
        /// </summary>
        public static string Pricing {
            get {
                return ResourceManager.GetString("Pricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طباعة معلومات ملف تعريف الطالب.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طباعة سؤال / مهمة / ورقة عمل.
        /// </summary>
        public static string Print_question {
            get {
                return ResourceManager.GetString("Print_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طباعة ملف تعريف المستخدم.
        /// </summary>
        public static string Print_User_Profile {
            get {
                return ResourceManager.GetString("Print_User_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طباعة ورقة عمل.
        /// </summary>
        public static string Print_Worksheet {
            get {
                return ResourceManager.GetString("Print_Worksheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to احترافي.
        /// </summary>
        public static string Pro {
            get {
                return ResourceManager.GetString("Pro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المنتجات.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محتوي الموقع.
        /// </summary>
        public static string ProjectPages {
            get {
                return ResourceManager.GetString("ProjectPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أنظمتنا هى الخيار الصحيح لأغراض كثيرة مثل: المحاسبة،الموارد البشرية والعديد من المجالات الأخرى..
        /// </summary>
        public static string Puposes {
            get {
                return ResourceManager.GetString("Puposes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحليل السؤال.
        /// </summary>
        public static string Question_analysis {
            get {
                return ResourceManager.GetString("Question_analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اي استفسارات ؟.
        /// </summary>
        public static string Questions {
            get {
                return ResourceManager.GetString("Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ريدموند.
        /// </summary>
        public static string Redmond {
            get {
                return ResourceManager.GetString("Redmond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رابط مرجعي.
        /// </summary>
        public static string Reference_link {
            get {
                return ResourceManager.GetString("Reference_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قد وضعت معايير السهوله والسرعه للسحابه الالكترونيه الخاصه بالمساند بغض النظر عن حجم المعاملات ..
        /// </summary>
        public static string regardless_volume {
            get {
                return ResourceManager.GetString("regardless_volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التسجيل.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد التسجيلات.
        /// </summary>
        public static string RegisteredCount {
            get {
                return ResourceManager.GetString("RegisteredCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التقارير.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يساعدك هذا البرنامج علي التقارير اللازمه وسهله لاي مستخدم يريد عمل تقارير بالقوائم اللازمه لبيانات مع شعارك الخاص.
        /// </summary>
        public static string Reports_Description {
            get {
                return ResourceManager.GetString("Reports_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادارة الادوار.
        /// </summary>
        public static string Roles_Admin {
            get {
                return ResourceManager.GetString("Roles_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موفر للوقت.
        /// </summary>
        public static string Save_time {
            get {
                return ResourceManager.GetString("Save_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة الجدول الزمني.
        /// </summary>
        public static string Schedule_management {
            get {
                return ResourceManager.GetString("Schedule_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to في كل دولة في العالم..
        /// </summary>
        public static string sector {
            get {
                return ResourceManager.GetString("sector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ضبط.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض جدول المقارنة.
        /// </summary>
        public static string Show_Comparison_Table {
            get {
                return ResourceManager.GetString("Show_Comparison_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to للحلول البرمجية.
        /// </summary>
        public static string SOFTWARE_SOLUTION {
            get {
                return ResourceManager.GetString("SOFTWARE_SOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قد وضعت معايير السهوله والسرعه للسحابه الالكترونيه الخاصه بالمساند بغض النظر عن حجم المعاملات..
        /// </summary>
        public static string Standards {
            get {
                return ResourceManager.GetString("Standards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المنصورة-شارع النخلة.
        /// </summary>
        public static string streat {
            get {
                return ResourceManager.GetString("streat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة الموضوعات.
        /// </summary>
        public static string Subjects_management {
            get {
                return ResourceManager.GetString("Subjects_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اشترك الان.
        /// </summary>
        public static string subscribe_now {
            get {
                return ResourceManager.GetString("subscribe_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاحد-الخميس.
        /// </summary>
        public static string Sunday_Thursday {
            get {
                return ResourceManager.GetString("Sunday_Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدعم الفني.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فريق الدعم الفني المباشر لمساعده عملائنا حيث خصصت الشركه فريق من المحترفين قادر علي مساعده العملاء والاجابه علي استفسارهم.
        /// </summary>
        public static string Support_Team {
            get {
                return ResourceManager.GetString("Support_Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المهمة.
        /// </summary>
        public static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدم (إدارة الطلاب والمعلمين).
        /// </summary>
        public static string Teacher_management {
            get {
                return ResourceManager.GetString("Teacher_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لشركة تك تاتش 2020.
        /// </summary>
        public static string Tech_Touch_Company {
            get {
                return ResourceManager.GetString("Tech_Touch_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تك تاتش.
        /// </summary>
        public static string TechTouch {
            get {
                return ResourceManager.GetString("TechTouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شركة تك تاتش للبرمجيات.
        /// </summary>
        public static string TechToutch {
            get {
                return ResourceManager.GetString("TechToutch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم اضافة الشكوي بنجاح.
        /// </summary>
        public static string Ticket_added_successfully {
            get {
                return ResourceManager.GetString("Ticket_added_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقارير عن الشكاوي.
        /// </summary>
        public static string Ticket_Reports {
            get {
                return ResourceManager.GetString("Ticket_Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *عملية تجارية.
        /// </summary>
        public static string Transaction {
            get {
                return ResourceManager.GetString("Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ العملية.
        /// </summary>
        public static string TransactionDate {
            get {
                return ResourceManager.GetString("TransactionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تجربة مجانية.
        /// </summary>
        public static string TrialFree {
            get {
                return ResourceManager.GetString("TrialFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد حدث خطأ غير متوقع. يرجى الاتصال بمسؤول النظام..
        /// </summary>
        public static string unexpected_error {
            get {
                return ResourceManager.GetString("unexpected_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد غير محدود من المستخدمين.
        /// </summary>
        public static string Unlimited_Users {
            get {
                return ResourceManager.GetString("Unlimited_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدم.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموعات المستخدمين.
        /// </summary>
        public static string UserGroups {
            get {
                return ResourceManager.GetString("UserGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رسالة المستخدم.
        /// </summary>
        public static string UserMessage {
            get {
                return ResourceManager.GetString("UserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إسم المستخدم.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدمين.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة المستخدمين.
        /// </summary>
        public static string Users_Admin {
            get {
                return ResourceManager.GetString("Users_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفيديوهات.
        /// </summary>
        public static string Vedios {
            get {
                return ResourceManager.GetString("Vedios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زورنا.
        /// </summary>
        public static string visit_us {
            get {
                return ResourceManager.GetString("visit_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الزوار.
        /// </summary>
        public static string VistorsCount {
            get {
                return ResourceManager.GetString("VistorsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نحن نهتم بعملائنا.
        /// </summary>
        public static string We_Care_Our_Customers {
            get {
                return ResourceManager.GetString("We_Care_Our_Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرحبا بكم فى موقع شركة تك تاتش للتكنولوجيا. اختيارك الأفضل لتجد حلول تكنولوجية تساعدك على انجاز أعمالك..
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بكود تحقق.
        /// </summary>
        public static string With_verification_code {
            get {
                return ResourceManager.GetString("With_verification_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مهمة مجموعة العمل.
        /// </summary>
        public static string Workgroup_task {
            get {
                return ResourceManager.GetString("Workgroup_task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إعداد ورقة العمل.
        /// </summary>
        public static string Worksheet_Setting {
            get {
                return ResourceManager.GetString("Worksheet_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحة الاتصال الخاصة بك..
        /// </summary>
        public static string Your_Contact_Page {
            get {
                return ResourceManager.GetString("Your_Contact_Page", resourceCulture);
            }
        }
    }
}
